services:
  just-loan-fcr-db:
    platform: linux/amd64
    image: postgres:12.20-alpine
    container_name: just-loan-fcr-db
    restart: always
    ports:
      - 5400:5400
    env_file:
      - .env
    volumes:
      - just-loan-fcr-db-vol:/var/lib/postgresql/data
    networks:
      - just-loan-fcr-net

networks:
  just-loan-fcr-net:
    name: just-loan-fcr-net
    external: true

volumes:
  just-loan-fcr-db-vol:
    driver: local
    name: just-loan-fcr-db-vol
